name: Terraform

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Create tfvars file
        run: echo "${{ secrets.TFVARS_CONTENT }}" > terraform.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ./tfplan

  terraform_apply:
    if: github.ref == 'refs/heads/main'
    needs: terraform_plan
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: .

      - name: Create tfvars file
        run: echo "${{ secrets.TFVARS_CONTENT }}" > terraform.tfvars

      - name: Terraform Apply
        run: terraform apply tfplan
